name: face_recognition
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/face.tflite
